services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bkk-esemkasari-app
    restart: unless-stopped
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
      - ./storage:/var/www/app/storage
      - ./bootstrap/cache:/var/www/app/bootstrap/cache
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - database

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: bkk-esemkasari-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # MySQL Database
  database:
    image: mysql:8.0
    container_name: bkk-esemkasari-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --skip-ssl
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3902:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
